name: Template-Plugin-Perl
version: 0.01
abstract: Perl Template Toolkit Plugin to Import Perl Built-in Functions
author: Agent Zhang <agent2002@126.com>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  File::Compare: 0
requires:
  Template: 0
  Data::Dumper: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
