abstract: TT2 plugin to import Perl built-in functions
author: 'Agent Zhang, <agentzh@gmail.com>'
build_requires:
  Test::Base: 0.53
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Template-Plugin-Perl
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  Template: 2.14
  perl: 5.6.1
version: 0.03
